version: '3'

services:
  cats-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: cats-api-builder
    ports:
      - "5173:5173"
    depends_on:
      - cats-client
    environment:
      - NODE_ENV=production

  cats-client:
    build:
      context: .
      dockerfile: Dockerfile
      target: cats-client-builder
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production